declare module 'markdown-yaml-metadata-parser'
declare module 'rehype-mathjax'
declare module '@akebifiky/remark-simple-plantuml'
declare module 'd3'
declare module 'd3-cloud'
declare module 'masonry-layout'
declare module 'imagesloaded'
declare module '*.jpeg'
