name: Check specification and code format on merge and pull request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-specification-and-code-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint check
        run: npm run lint

      - name: Run Prettier check
        run: npm run prettier

      - name: Run unit tests
        run: npm run test:unit
